apiVersion: v1
kind: ServiceAccount
metadata:
  # TODO: Set defaults for case no custom values are being supplied from the TES Task Tags
  name: funnel-worker-sa-{{.Namespace}}-{{.TaskId}}
  namespace: {{.Namespace}}
  labels:
    app: funnel
    taskId: {{.TaskId}}
  annotations:
    # set this with value of OIDC_IAM_ROLE
    eks.amazonaws.com/role-arn: {{.IamRoleArn}}
spec:
  # TODO: Should tokens be automatically mounted into pods?
  automountServiceAccountToken: false
