apiVersion: v1
kind: PersistentVolume
metadata:
  name: funnel-worker-pv-{{.TaskId}}
  labels:
    app: funnel
    taskId: {{.TaskId}}
spec:
  storageClassName: "" # Required for static provisioning
  capacity:
    storage: "10Mi"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - allow-delete
    - allow-overwrite
    - region={{.Region}}
    - file-mode=0755
    - sse aws:kms
    - sse-kms-key-id={{.KmsKeyID}}
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-{{.TaskId}}
    volumeAttributes:
      bucketName: {{.Bucket}}
  claimRef:
    namespace: {{.Namespace}}
    name: funnel-worker-pvc-{{.TaskId}}
