# Funnel Worker
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.TaskId}}
  namespace: {{.JobsNamespace}}
  labels:
    app: funnel-worker
    task-id: {{.TaskId}}
    # Custom Labels support
    {{- range $key, $value := .ExtraLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  backoffLimit: 1
  completions: 1
  template:
    metadata:
      labels:
        app: funnel-worker
        task-id: {{.TaskId}}
    spec:
      serviceAccountName: funnel-sa-{{.Namespace}}
      restartPolicy: OnFailure
      containers:
        - name: funnel-worker-{{.TaskId}}
          # TODO: Make the image + tag configurable
          image: {{.Image}}
          imagePullPolicy: Always
          args:
            - "worker"
            - "run"
            - "--config"
            - "/etc/config/funnel-worker.yaml"
            - "--taskID"
            - {{.TaskId}}
          resources:
            requests:
              cpu: {{if ne .Cpus 0 -}}{{.Cpus}}{{ else }}{{"100m"}}{{end}}
              memory: {{if ne .RamGb 0.0 -}}{{printf "%.0fG" .RamGb}}{{else}}{{"16M"}}{{end}}
              ephemeral-storage: {{if ne .DiskGb 0.0 -}}{{printf "%.0fG" .DiskGb}}{{else}}{{"100M"}}{{end}}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config

          - name: funnel-storage-{{.TaskId}}
            mountPath: /opt/funnel/funnel-work-dir/{{.TaskId}}
            subPath: {{.TaskId}}

      volumes:
      - name: config-volume
        configMap:
          name: funnel-worker-config-{{.TaskId}}

      - name: funnel-storage-{{.TaskId}}
        persistentVolumeClaim:
          claimName: funnel-worker-pvc-{{.TaskId}}
