DBPath: /opt/funnel/funnel.db
ContentDir: /opt/funnel/share
WorkDir: /mnt/disks/shared/funnel-work-dir
HTTPPort: 80
Scheduler: gce
Schedulers:
  GCE:
    Project: isb-cgc-04-0029
    Zone: us-west1-b
    Templates:
    - funnel-worker-8
Storage:
- Local:
  AllowedDirs:
    /mnt/disks/shared
- GS:
  FromEnv: true
