languageCode: en-us
title: Funnel
publishDir: ../docs
assetDir: assets
menu:
  main:
    - name: Reference â†—
      parent: Development
      url: https://godoc.org/github.com/ohsu-comp-bio/funnel
      weight: 30
security:
  funcs:
    getenv:
      - ^FUNNEL_
markup:
  goldmark:
    renderer:
      unsafe: true
module:
  imports:
    - path: github.com/KKKZOZ/hugo-admonitions
